### PR TITLE
Made zero immuatble, added support for numeric registers

### LINKED ISSUE #76: [BUG] the $zero register is writable
**Environment (please complete the following information):**
 - OS: Any

**Describe the bug**
`move $zero 10` sets the `$zero` register to 10. It shouldn't.

**Expected behavior**
Should stay at 0

### PR DESCRIPTION
**Pull request by WyattRoss**
resolves #76

### CODE REVIEW

File: rezasm-source/rezasm-core/src/simulation/registry.rs [hunk 1]
```diff
@@ -134,6 +140,22 @@ pub fn is_valid_register(register: &String) -> bool {
...
+    if register.len() < 1 {
+        return false;
+    }
+    let mut temp = register.clone();
+    if register.starts_with("$") {
+        temp.remove(0);
+    }
+    let index = temp.parse::<usize>();
+
+    match index {
```
Comment (TrevorBrunette) [inline rezasm-source/rezasm-core/src/simulation/registry.rs:153]: We should check if the number is proper in parsing here

**Review by TrevorBrunette — COMMENTED** [review]
Please fix

**Review by TrevorBrunette — APPROVED** [review]
Looks good now
